### ISSUE TITLE
Digital memcomputing repository

### ISSUE THREAD

**Issue by TheeDarkSeraph** [maxtuno/HESS-SAT-COMPLETE#1]
Hello Daniel,
This is not an issue, but I have not found any other means of contacting you.
I saw in this post:
https://cstheory.stackexchange.com/questions/37384/does-memcomputing-really-solve-an-np-complete-problem
That you said you had a public repository dmm of the implementation of the digital memcomputer (at least I assume the circuits were implemented as in the paper). I was wondering if you have any issues sharing it as I would like to test and use it.
If not, then sorry for the bother. I've been looking for sources to help me implement the paper and yours is the only one I could find.
My email if you want to contact me:
s.elabyad@fci-cu.edu.eg

**Comment by maxtuno** [comment]
I'm sorry but I think you're wrong about something, the HESS algorithm is my creation, second, I haven't commented anything on that site and mi name is Oscar Riveros...  www.oscarriveros.art

Hess is an algorithm that I created about a decade ago, and it has many applications to approximate and "solve" NP-Complete and NP-Hard problems... I recommend you check my profile, there are several implementations for different problems...

HESS is a black box algorithm, it has nothing to do with what you mention, unless they had used my work for some publication without notifying me...

Greetings.

**Comment by TheeDarkSeraph** [comment]
Oh you're right. I deeply apologize for the misunderstanding. I meant to contact someone else through his github projects so I choose one in his repositories, but it seems I've gone to your repository through him because it was a forked project from your repository (I only use basic functionallities of git, I thought I was on his page).
Hopefully, I don't repeat this mistake, and I am sorry to alarm you for no reason. I was trying to get help in something specific.

Thanks for replying and have a nice day.
